name: Mystic
favicon: null
layout_spectrum: 0.5695885336026549
typography_spectrum: 0.13031333242543042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3145164984744042
  lightness: 0.15358580253086984
  saturation: 0.449774706736207
  rhythmicContrast: 0.6546999989077449
purpose: []
